Redux setup and data persist
Dverybest/evakitchen_admin pull request #1
Opened 2021-05-16 21:06 UTC by NancyRike

2021-05-16 21:41 UTC, Dverybest requested changes

2021-05-16 21:41 UTC, Dverybest commented on src/reduxStore/Reducers/authReducer.ts
> +                return{...state, isAuthenticated: action.type }
Can we combine this two
to
            case USER_DETAILS:
                return{...state,isAuthenticated:true, userDetails: action.type}

2021-05-16 21:41 UTC, Dverybest commented on src/reduxStore/Reducers/authReducer.ts
> +                return {...state, token: action.type}
you should not  action.type rather action.payload
this should be
 case USER_DETAILS:
                return{...state, userDetails: action.payload}
            case TOKEN:
                return {...state, token: action.payload}

2021-05-16 21:41 UTC, Dverybest commented on src/reduxStore/actions/authAction.ts
> +const AuthAction = (payload:payloadType)=>{
can you change this to
const AuthAction = (payload:any)=>{

2021-05-16 21:41 UTC, Dverybest commented on src/reduxStore/actions/authAction.ts
> +interface payloadType {
No need for this

2021-05-16 21:41 UTC, Dverybest commented on src/reduxStore/store.js
> +    return createStore(RootReducer, applyMiddleware (thunk));
Add middleware to persist data to sessionStorage

2021-05-17 08:30 UTC, NancyRike commented on src/reduxStore/Reducers/authReducer.ts
> +                return{...state, isAuthenticated: action.type }
okay will do

2021-05-20 23:10 UTC, Dverybest approved these changes

2021-05-20 23:10 UTC, merged